class_name FlowErrorCodes
extends RefCounted

## Canonical Error Codes for GameFlow and StageOrchestrator.

const INVALID_STAGE_ID: String = "ERR_INVALID_STAGE_ID"
const STAGE_LOCKED: String = "ERR_STAGE_LOCKED"
const INVALID_LIFECYCLE_TRANSITION: String = "ERR_INVALID_LIFECYCLE_TRANSITION"
const DUPLICATE_CALLBACK: String = "ERR_DUPLICATE_CALLBACK"
const COMBAT_NOT_ALLOWED: String = "ERR_COMBAT_NOT_ALLOWED"
const INVALID_CONTENT_REFERENCE: String = "ERR_INVALID_CONTENT_REFERENCE"
const SAVE_RESTORE_FAILED: String = "ERR_SAVE_RESTORE_FAILED"
const QUESTION_SESSION_FAILED: String = "ERR_QUESTION_SESSION_FAILED"
